refold-ease: fix typing to not crash on startup
list[tuple] is not the correct way of referencing the type, and causes
a TypeError when the add-on is loaded:

  When loading '⁨RefoldEase⁩':
  ⁨Traceback (most recent call last):
    File "aqt/addons.py", line 211, in loadAddons
    File "/home/cyphar/.local/share/Anki2/addons21/RefoldEase/__init__.py", line 153, in <module>
      def getDecksInfo() -> list[tuple]:
  TypeError: 'type' object is not subscriptable

The correct way is to import typing and use List[Tuple].

Fixes: 101bbe15a9c1 ("allow the user to limit change of ease factors to a selected deck")
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>